name: connectinno
description: A simple Flutter app with mock authentication
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_bloc: ^8.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^1.5.0

flutter:
  uses-material-design: true
